// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LineKeywordMatcher.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class LINE關鍵字偵測Feature : object, Xunit.IClassFixture<LINE關鍵字偵測Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "LineKeywordDetection.feature"
#line hidden
        
        public LINE關鍵字偵測Feature(LINE關鍵字偵測Feature.FixtureData fixtureData, LineKeywordMatcher_Specs_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "LINE 關鍵字偵測", "    身為內容審核人員\r\n    我想要偵測包含 LINE 聯絡方式的訊息\r\n    以便進行審查", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="偵測各種格式的 LINE 關鍵字")]
        [Xunit.TraitAttribute("FeatureTitle", "LINE 關鍵字偵測")]
        [Xunit.TraitAttribute("Description", "偵測各種格式的 LINE 關鍵字")]
        [Xunit.InlineDataAttribute("留下LINE", "true", new string[0])]
        [Xunit.InlineDataAttribute("留下line", "true", new string[0])]
        [Xunit.InlineDataAttribute("留下Line", "true", new string[0])]
        [Xunit.InlineDataAttribute("留下 LINE", "true", new string[0])]
        [Xunit.InlineDataAttribute("留 下 LINE", "true", new string[0])]
        [Xunit.InlineDataAttribute("留下ＬＩＮＥ", "true", new string[0])]
        [Xunit.InlineDataAttribute("留下ｌｉｎｅ", "true", new string[0])]
        [Xunit.InlineDataAttribute("留下 Ｌｉｎｅ", "true", new string[0])]
        [Xunit.InlineDataAttribute("留下賴", "true", new string[0])]
        [Xunit.InlineDataAttribute("留 下 賴", "true", new string[0])]
        [Xunit.InlineDataAttribute("留下　LINE", "true", new string[0])]
        [Xunit.InlineDataAttribute("請留下LINE聯絡", "true", new string[0])]
        [Xunit.InlineDataAttribute("今天天氣很好", "false", new string[0])]
        [Xunit.InlineDataAttribute("LINE好用", "false", new string[0])]
        [Xunit.InlineDataAttribute("留下電話", "false", new string[0])]
        public void 偵測各種格式的LINE關鍵字(string input, string expected, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("input", input);
            argumentsOfScenario.Add("expected", expected);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("偵測各種格式的 LINE 關鍵字", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
        testRunner.Given(string.Format("輸入文字為 \"{0}\"", input), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
        testRunner.When("檢查是否包含 LINE 關鍵字", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 9
        testRunner.Then(string.Format("結果應為 {0}", expected), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                LINE關鍵字偵測Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                LINE關鍵字偵測Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
